/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.53
 * Generated at: 2020-06-11 01:33:18 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.keshe;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class register_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=gb2312");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"gb2312\">\r\n");
      out.write("<title>注册界面</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/init.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/public.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/regi.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div class=\"header w\">\r\n");
      out.write("\t\t<div class=\"logo\">\r\n");
      out.write("\t\t\t<img src=\"images/logo.jpg\" alt=\"\" />\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"login\">\r\n");
      out.write("\t\t\t<ul>\r\n");
      out.write("\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t<a href=\"login.jsp\">登录</a> |\r\n");
      out.write("\t\t\t\t\t<a href=\"register.jsp\">注册</a>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- 导航栏 -->\r\n");
      out.write("\t<div class=\"nav w\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<ul class=\"left\">\r\n");
      out.write("\t\t    \t<li><a href=\"index.jsp\" >首页</a></li>\r\n");
      out.write("\t\t    \t<li><a href=\"#\" >博客</a></li>\r\n");
      out.write("\t\t    \t<li><a href=\"#\" >论坛</a></li>\r\n");
      out.write("\t\t    \t<li><a href=\"#\" >棋事</a></li>\r\n");
      out.write("\t\t    \t<li><a href=\"xianshangweiqi.jsp\" >线上围棋</a></li>\r\n");
      out.write("\t\t    \t<li><a href=\"bangzhu.jsp\" >帮助</a></li>\r\n");
      out.write("\t\t    \t<li><a href=\"chongzhi.jsp\" >充值</a></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("  \t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"main w\">\r\n");
      out.write("\t\t<div class=\"border w\">注册围棋账号</div>\r\n");
      out.write("\t\t<form action=\"insertServlet?dataBase=weiqiluntan&tableName=chess_user\" name=\"register\" method=\"post\">\r\n");
      out.write("                <input name=\"username\" type=\"text\" placeholder=\"请输入账号\" class=\"code\">\r\n");
      out.write("                <input name=\"password\" data-a=\"a1\" type=\"password\" placeholder=\"请输入密码\" class=\"code\">\r\n");
      out.write("                <input name=\"phone\" type=\"text\" placeholder=\"请输入电话\" class=\"code\">\r\n");
      out.write("                <input name=\"sex\" type=\"text\" placeholder=\"请输入性别\" class=\"code\">\r\n");
      out.write("                <div class=\"lf\">\r\n");
      out.write("                    <input type=\"checkbox\" checked>\r\n");
      out.write("                                                        已阅读并同意<a href=\"\">《围棋账号注册协议》</a>\r\n");
      out.write("                </div>\r\n");
      out.write("                <input type=\"submit\" value=\"立即注册\" class=\"now-register\">\r\n");
      out.write("         </form>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"footer\">\r\n");
      out.write("    \t<p>围棋论坛小组 版权所有</p>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
